
#!/bin/bash

# Simple backup script
timestamp=$(date +%Y%m%d_%H%M%S)
backup_dir="backups/$timestamp"

mkdir -p "$backup_dir"
cp -r src/ "$backup_dir/"
cp -r public/ "$backup_dir/"
cp package.json "$backup_dir/"

echo "Backup created in $backup_dir"
