
name: Backup

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create backup
        run: |
          timestamp=$(date +%Y%m%d_%H%M%S)
          backup_dir="backups/$timestamp"
          mkdir -p "$backup_dir"
          cp -r src/ "$backup_dir/"
          cp -r public/ "$backup_dir/"
          cp package.json "$backup_dir/"
          
      - name: Upload backup
        uses: actions/upload-artifact@v3
        with:
          name: project-backup
          path: backups/
