
name: Backup

on:
  push:
    branches: [ main, dev ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Backup
        run: |
          timestamp=$(date +%Y%m%d_%H%M%S)
          mkdir -p "backup_${timestamp}"
          cp -r src/ "backup_${timestamp}/"
          cp -r public/ "backup_${timestamp}/"
          cp package.json "backup_${timestamp}/"
          
      - uses: actions/upload-artifact@v3
        with:
          name: backup
          path: backup_*
          retention-days: 7
