name: Backup

on:
  push:
    branches: [ main, dev ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Export Database
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-service-account.json
          npx -y firestore-export-import backup/firestore.json
        continue-on-error: true

      - name: Create Backup
        run: |
          mkdir -p backups
          timestamp=$(date +%Y%m%d-%H%M%S)
          git archive --format=tar.gz -o backups/backup-$timestamp.tar.gz HEAD
          if [ -f backup/firestore.json ]; then
            cp backup/firestore.json backups/firestore-$timestamp.json
          fi

      - name: Upload Backup
        uses: actions/upload-artifact@v3
        with:
          name: backup-${{ github.sha }}
          path: backups/
          retention-days: 30

      - name: Notify on Success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '✅ Backup completed successfully'
            })

      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '❌ Backup failed'
            })
