
name: Backup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Backup
        run: |
          zip -r backup.zip src/ public/ package.json README.md tsconfig.json
          
      - uses: actions/upload-artifact@v3
        with:
          name: backup
          path: backup.zip
          retention-days: 7
